### ISSUE TITLE
rutube ModuleNotFoundError

### ISSUE THREAD

**Issue by johndoe71rus** [Zeltorix/kodi#1]
Сломался плагин
```
2023-11-30 21:28:04.183 T:229563   DEBUG <general>: CPythonInvoker(35, /home/johndoe/.kodi/addons/plugin.video.zeltorix.rutube/addon.py): instantiating addon using automatically obtained id of "plugin.video.zeltorix.rutube" dependent on version 3.0.0 of the xbmc.python api
2023-11-30 21:28:05.236 T:229563   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'view_base'
                                                   Traceback (most recent call last):
                                                     File "/home/johndoe/.kodi/addons/plugin.video.zeltorix.rutube/addon.py", line 12, in <module>
                                                       from resources.lib.router import router
                                                     File "/home/johndoe/.kodi/addons/plugin.video.zeltorix.rutube/resources/lib/router.py", line 13, in <module>
                                                       from .model import ModelRutube
                                                     File "/home/johndoe/.kodi/addons/plugin.video.zeltorix.rutube/resources/lib/model.py", line 15, in <module>
                                                       from view_base import View as BaseView
                                                   ModuleNotFoundError: No module named 'view_base'
                                                   -->End of Python script error report<--
```

ps.  форум похоже все (

**Comment by Zeltorix** [comment]
Исправлено.
У тебя, случаем, столько не завалялось, чтобы форум вернуть?)))
